package works.hop.jdbc.i_4_insert_1_to_1;

public class ColumnInfo {

    String columnName;
    String attributeName;
    Class<?> attributeType;
    Boolean isAutoGenerated;
    Boolean isEmbedded;
    Boolean isEnum;
    Boolean isEnumOrdinal;
    Boolean isCompositePk;
    Boolean isPkColumn;
    Boolean isFkColumn;
    String[][] compositeColumns;

    public ColumnInfo(String columnName, String attributeName, Class<?> attributeType, Boolean isAutoGenerated, Boolean isEmbedded, Boolean isEnum,
                      Boolean isEnumOrdinal, Boolean isCompositePk, Boolean isPkColumn, Boolean isFkColumn, String[][] compositeColumns) {
        this.columnName = columnName;
        this.attributeName = attributeName;
        this.attributeType = attributeType;
        this.isAutoGenerated = isAutoGenerated;
        this.isEmbedded = isEmbedded;
        this.isEnum = isEnum;
        this.isEnumOrdinal = isEnumOrdinal;
        this.isCompositePk = isCompositePk;
        this.isPkColumn = isPkColumn;
        this.isFkColumn = isFkColumn;
        this.compositeColumns = compositeColumns;
    }

    public static ColumnInfoBuilder builder() {
        return new ColumnInfoBuilder();
    }
}
