package works.hop.jdbc.i_1_insert_basic;

public class ColumnInfo {

    String columnName;
    String attributeName;
    Class<?> attributeType;
    Boolean isAutoGenerated;

    public ColumnInfo(String columnName, String attributeName, Class<?> attributeType, Boolean isAutoGenerated) {
        this.columnName = columnName;
        this.attributeName = attributeName;
        this.attributeType = attributeType;
        this.isAutoGenerated = isAutoGenerated;
    }
}
