package works.hop.jdbc.i_2_insert_embedded;

public class ColumnInfo {

    String columnName;
    String attributeName;
    Class<?> attributeType;
    Boolean isAutoGenerated;

    public ColumnInfo(String columnName, String attributeName, Class<?> attributeType, Boolean isAutoGenerated) {
        this.columnName = columnName;
        this.attributeName = attributeName;
        this.attributeType = attributeType;
        this.isAutoGenerated = isAutoGenerated;
    }
}
