package works.hop.jdbc.i_3_insert_composite_key;

public class ColumnInfo {

    String columnName;
    String attributeName;
    Class<?> attributeType;
    Boolean isAutoGenerated;
    Boolean isEmbedded;
    Boolean isEnum;
    Boolean isCompositePk;

    public ColumnInfo(String columnName, String attributeName, Class<?> attributeType, Boolean isAutoGenerated, Boolean isEmbedded, Boolean isEnum, Boolean isCompositePk) {
        this.columnName = columnName;
        this.attributeName = attributeName;
        this.attributeType = attributeType;
        this.isAutoGenerated = isAutoGenerated;
        this.isEmbedded = isEmbedded;
        this.isEnum = isEnum;
        this.isCompositePk = isCompositePk;
    }

    public static ColumnInfoBuilder builder() {
        return new ColumnInfoBuilder();
    }
}
