package works.hop.jdbc.i_6_insert_join_different_tables;

import works.hop.jdbc.i_0_insert.EntityMappingException;

import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public abstract class EntityMetadata {

    final String tableName;
    final EntityType entityType;
    final Set<ColumnInfo> columns;

    public EntityMetadata(Class<? extends Entity> entityClass, String tableName, Set<ColumnInfo> columns) {
        this(entityClass, tableName, columns, EntityType.IDENTIFIABLE);
    }

    public EntityMetadata(Class<? extends Entity> entityClass, String tableName, Set<ColumnInfo> columns, EntityType entityType) {
        this.tableName = tableName;
        this.entityType = entityType;
        this.columns = columns;
        EntityRegistry.registry.put(entityClass, this);
    }

    public abstract <T extends Entity> T entityInstance();

    public Optional<ColumnInfo> resolveByColumnName(String columnName) {
        return columns.stream()
                .filter(info -> info.columnName != null)
                .filter(info -> info.columnName.equals(columnName))
                .findFirst();
    }

    public ColumnInfo pkColumn() {
        return columns.stream().filter(info -> info.isPkColumn).findFirst().orElseThrow();
    }

    public Boolean containsPkColumn() {
        return columns.stream().anyMatch(info -> info.isPkColumn != null && info.isPkColumn);
    }

    public Boolean containsEmbedded() {
        return columns.stream().anyMatch(info -> info.isEmbedded != null && info.isEmbedded);
    }

    public List<ColumnInfo> embeddedColumns() {
        return columns.stream().filter(info -> info.isEmbedded).collect(Collectors.toList());
    }

    public Boolean containsCompositePk() {
        return columns.stream().anyMatch(info -> info.isCompositePk != null && info.isCompositePk);
    }

    public ColumnInfo compositePkColumn() {
        return columns.stream().filter(info -> info.isCompositePk).findFirst().orElseThrow(
                () -> new EntityMappingException("There is no composite pk key column defined in the metadata")
        );
    }

    public boolean containsGenerated() {
        return columns.stream().anyMatch(info -> info.isAutoGenerated);
    }

    public ColumnInfo generatedColumn() {
        return columns.stream().filter(info -> info.isAutoGenerated).findFirst().orElseThrow(
                () -> new EntityMappingException("There is no auto-generated column defined in the metadata"));
    }

    public Boolean containsFkColumns() {
        return columns.stream().anyMatch(info -> info.isFkColumn != null && info.isFkColumn);
    }

    public List<ColumnInfo> fkColumns() {
        return columns.stream().filter(info -> info.isFkColumn).collect(Collectors.toList());
    }

    public Boolean containsCollectionColumns() {
        return columns.stream().anyMatch(info -> info.isCollection != null && info.isCollection);
    }

    public List<ColumnInfo> collectionColumns() {
        return columns.stream().filter(info -> info.isCollection).collect(Collectors.toList());
    }

    public String createInsertQuery(String[] columnNames) {
        //"insert into :TABLE_NAME (f:COLUMN_NAMES) value (:PLACEHOLDERS)";
        StringBuilder builder = new StringBuilder();
        builder.append("insert into ").append(tableName).append(" (");
        for (int i = 0; i < columnNames.length; i++) {
            String columnName = columnNames[i];
            builder.append(columnName);
            if (i + 1 < columnNames.length) {
                builder.append(", ");
            }
        }
        builder.append(") values (")
                .append(IntStream.range(0, columnNames.length).mapToObj(i -> "?").collect(Collectors.joining(",")))
                .append(")");
        return builder.toString();
    }
}
